// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/agent.proto

// Package agent defines the gRPC service that the agent core exposes to
// out-of-process channel adapters (Telegram, WhatsApp, Discord, etc.).
//
// Current status: DESIGN — v1 adapters run in-process using the plugin.Adapter
// interface. This protobuf is the planned contract for v2 out-of-process adapters.
// Generate Go code with `make proto`.

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChannelAdapter_SendMessage_FullMethodName    = "/agent.ChannelAdapter/SendMessage"
	ChannelAdapter_StreamMessages_FullMethodName = "/agent.ChannelAdapter/StreamMessages"
	ChannelAdapter_Health_FullMethodName         = "/agent.ChannelAdapter/Health"
)

// ChannelAdapterClient is the client API for ChannelAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChannelAdapter is the gRPC service implemented by each out-of-process adapter.
// The adapter acts as both CLIENT (sending inbound messages to core) and SERVER
// (receiving outbound messages from core).
//
// In v2, the agent core will expose this service over a Unix socket or localhost
// gRPC port that each adapter binary connects to on startup.
type ChannelAdapterClient interface {
	// SendMessage delivers an agent response to the user via the adapter.
	SendMessage(ctx context.Context, in *OutboundMessage, opts ...grpc.CallOption) (*SendResult, error)
	// StreamMessages is a bidirectional stream: the adapter pushes InboundMessages
	// and receives Acks; the core pushes OutboundMessages back on the same stream.
	StreamMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InboundMessage, OutboundMessage], error)
	// Health reports adapter readiness.
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
}

type channelAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelAdapterClient(cc grpc.ClientConnInterface) ChannelAdapterClient {
	return &channelAdapterClient{cc}
}

func (c *channelAdapterClient) SendMessage(ctx context.Context, in *OutboundMessage, opts ...grpc.CallOption) (*SendResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResult)
	err := c.cc.Invoke(ctx, ChannelAdapter_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAdapterClient) StreamMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InboundMessage, OutboundMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChannelAdapter_ServiceDesc.Streams[0], ChannelAdapter_StreamMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InboundMessage, OutboundMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelAdapter_StreamMessagesClient = grpc.BidiStreamingClient[InboundMessage, OutboundMessage]

func (c *channelAdapterClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, ChannelAdapter_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelAdapterServer is the server API for ChannelAdapter service.
// All implementations must embed UnimplementedChannelAdapterServer
// for forward compatibility.
//
// ChannelAdapter is the gRPC service implemented by each out-of-process adapter.
// The adapter acts as both CLIENT (sending inbound messages to core) and SERVER
// (receiving outbound messages from core).
//
// In v2, the agent core will expose this service over a Unix socket or localhost
// gRPC port that each adapter binary connects to on startup.
type ChannelAdapterServer interface {
	// SendMessage delivers an agent response to the user via the adapter.
	SendMessage(context.Context, *OutboundMessage) (*SendResult, error)
	// StreamMessages is a bidirectional stream: the adapter pushes InboundMessages
	// and receives Acks; the core pushes OutboundMessages back on the same stream.
	StreamMessages(grpc.BidiStreamingServer[InboundMessage, OutboundMessage]) error
	// Health reports adapter readiness.
	Health(context.Context, *Empty) (*HealthStatus, error)
	mustEmbedUnimplementedChannelAdapterServer()
}

// UnimplementedChannelAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelAdapterServer struct{}

func (UnimplementedChannelAdapterServer) SendMessage(context.Context, *OutboundMessage) (*SendResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChannelAdapterServer) StreamMessages(grpc.BidiStreamingServer[InboundMessage, OutboundMessage]) error {
	return status.Error(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedChannelAdapterServer) Health(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedChannelAdapterServer) mustEmbedUnimplementedChannelAdapterServer() {}
func (UnimplementedChannelAdapterServer) testEmbeddedByValue()                        {}

// UnsafeChannelAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelAdapterServer will
// result in compilation errors.
type UnsafeChannelAdapterServer interface {
	mustEmbedUnimplementedChannelAdapterServer()
}

func RegisterChannelAdapterServer(s grpc.ServiceRegistrar, srv ChannelAdapterServer) {
	// If the following call panics, it indicates UnimplementedChannelAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelAdapter_ServiceDesc, srv)
}

func _ChannelAdapter_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutboundMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdapterServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdapter_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdapterServer).SendMessage(ctx, req.(*OutboundMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAdapter_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChannelAdapterServer).StreamMessages(&grpc.GenericServerStream[InboundMessage, OutboundMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelAdapter_StreamMessagesServer = grpc.BidiStreamingServer[InboundMessage, OutboundMessage]

func _ChannelAdapter_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdapterServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdapter_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdapterServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelAdapter_ServiceDesc is the grpc.ServiceDesc for ChannelAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.ChannelAdapter",
	HandlerType: (*ChannelAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _ChannelAdapter_SendMessage_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ChannelAdapter_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _ChannelAdapter_StreamMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}

const (
	AgentCore_Chat_FullMethodName   = "/agent.AgentCore/Chat"
	AgentCore_Health_FullMethodName = "/agent.AgentCore/Health"
)

// AgentCoreClient is the client API for AgentCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentCore is the gRPC service the agent core will expose to adapters.
// Adapters call this to submit messages and receive streaming responses.
type AgentCoreClient interface {
	// Chat submits a user message and streams back the agent's response.
	Chat(ctx context.Context, in *InboundMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OutboundMessage], error)
	// Health returns core readiness.
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
}

type agentCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentCoreClient(cc grpc.ClientConnInterface) AgentCoreClient {
	return &agentCoreClient{cc}
}

func (c *agentCoreClient) Chat(ctx context.Context, in *InboundMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OutboundMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentCore_ServiceDesc.Streams[0], AgentCore_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InboundMessage, OutboundMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentCore_ChatClient = grpc.ServerStreamingClient[OutboundMessage]

func (c *agentCoreClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, AgentCore_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentCoreServer is the server API for AgentCore service.
// All implementations must embed UnimplementedAgentCoreServer
// for forward compatibility.
//
// AgentCore is the gRPC service the agent core will expose to adapters.
// Adapters call this to submit messages and receive streaming responses.
type AgentCoreServer interface {
	// Chat submits a user message and streams back the agent's response.
	Chat(*InboundMessage, grpc.ServerStreamingServer[OutboundMessage]) error
	// Health returns core readiness.
	Health(context.Context, *Empty) (*HealthStatus, error)
	mustEmbedUnimplementedAgentCoreServer()
}

// UnimplementedAgentCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentCoreServer struct{}

func (UnimplementedAgentCoreServer) Chat(*InboundMessage, grpc.ServerStreamingServer[OutboundMessage]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAgentCoreServer) Health(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAgentCoreServer) mustEmbedUnimplementedAgentCoreServer() {}
func (UnimplementedAgentCoreServer) testEmbeddedByValue()                   {}

// UnsafeAgentCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentCoreServer will
// result in compilation errors.
type UnsafeAgentCoreServer interface {
	mustEmbedUnimplementedAgentCoreServer()
}

func RegisterAgentCoreServer(s grpc.ServiceRegistrar, srv AgentCoreServer) {
	// If the following call panics, it indicates UnimplementedAgentCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentCore_ServiceDesc, srv)
}

func _AgentCore_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InboundMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentCoreServer).Chat(m, &grpc.GenericServerStream[InboundMessage, OutboundMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentCore_ChatServer = grpc.ServerStreamingServer[OutboundMessage]

func _AgentCore_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentCoreServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentCore_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentCoreServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentCore_ServiceDesc is the grpc.ServiceDesc for AgentCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentCore",
	HandlerType: (*AgentCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AgentCore_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AgentCore_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
