package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/openclio/openclio/internal/workspace"
)

// runInit is the interactive first-time setup wizard.
// It runs BEFORE any config or database is loaded so it works on a fresh install.
func runInit(dataDir string) {
	configPath := filepath.Join(dataDir, "config.yaml")

	fmt.Println()
	fmt.Println("┌──────────────────────────────────────────────────┐")
	fmt.Println("│  Welcome to openclio — Your Personal AI Agent  │")
	fmt.Println("└──────────────────────────────────────────────────┘")

	// Check for existing config
	if _, err := os.Stat(configPath); err == nil {
		fmt.Printf("Config already exists at %s\n", configPath)
		if !promptConfirm("Overwrite it?", false) {
			fmt.Println("Setup cancelled. Your existing config is unchanged.")
			os.Exit(0)
		}
	}

	// Ensure data directory exists
	if err := os.MkdirAll(dataDir, 0700); err != nil {
		fmt.Fprintf(os.Stderr, "error creating %s: %v\n", dataDir, err)
		os.Exit(1)
	}

	// Seed bundled default skills without overwriting any existing user skills.
	if err := workspace.SeedDefaultSkills(dataDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: failed to seed default skills: %v\n", err)
	}

	assistantName := promptString("What should your assistant be called? [Aria]", "Aria")
	fmt.Println()
	fmt.Println("Tell me a bit about yourself — this will be saved in user context.")
	fmt.Println("(Finish with an empty line)")
	userProfile := promptMultiline("> ")
	if strings.TrimSpace(userProfile) == "" {
		userProfile = "I am a developer and prefer concise, practical answers."
	}
	fmt.Println()

	fmt.Println("Which channels should be enabled?")
	fmt.Println("  [x] CLI (always enabled)")
	enableTelegram := promptConfirm("Enable Telegram?", false)
	enableDiscord := promptConfirm("Enable Discord?", false)
	enableWhatsApp := promptConfirm("Enable WhatsApp?", false)
	enableWebChat := promptConfirm("Enable WebChat (localhost UI)?", false)
	fmt.Println()

	fmt.Println("Which AI model provider?")
	fmt.Println("  1) Anthropic Claude (recommended)")
	fmt.Println("  2) OpenAI GPT")
	fmt.Println("  3) Google Gemini")
	fmt.Println("  4) Ollama (local, free, private)")
	providerChoice := promptChoice("Choose provider", []string{"1", "2", "3", "4"}, "1")

	var provider, defaultModel, apiKeyEnv, apiKeyHint string
	switch providerChoice {
	case "1":
		provider = "anthropic"
		defaultModel = "claude-sonnet-4-20250514"
		apiKeyEnv = "ANTHROPIC_API_KEY"
		apiKeyHint = "https://console.anthropic.com/settings/keys"
	case "2":
		provider = "openai"
		defaultModel = "gpt-4o-mini"
		apiKeyEnv = "OPENAI_API_KEY"
		apiKeyHint = "https://platform.openai.com/api-keys"
	case "3":
		provider = "gemini"
		defaultModel = "gemini-1.5-flash"
		apiKeyEnv = "GEMINI_API_KEY"
		apiKeyHint = "https://aistudio.google.com/app/apikey"
	default:
		provider = "ollama"
		defaultModel = "llama3.1"
	}

	fmt.Println()

	model := promptString(fmt.Sprintf("Model name [%s]", defaultModel), defaultModel)
	fmt.Println()
	portStr := promptString("HTTP port [18789]", "18789")
	port, err := strconv.Atoi(portStr)
	if err != nil || port < 1 || port > 65535 {
		fmt.Fprintf(os.Stderr, "invalid port: %s\n", portStr)
		os.Exit(1)
	}
	if provider != "ollama" {
		apiKeyEnv = promptString(fmt.Sprintf("API key env var [%s]", apiKeyEnv), apiKeyEnv)
	}

	fmt.Println()

	// ── Build YAML ────────────────────────────────────────────────────────────
	var sb strings.Builder

	sb.WriteString("# Agent configuration\n")
	sb.WriteString("# Generated by 'agent init'. Edit freely.\n\n")

	sb.WriteString("model:\n")
	sb.WriteString(fmt.Sprintf("  provider:    %s\n", provider))
	sb.WriteString(fmt.Sprintf("  model:       %s\n", model))
	if apiKeyEnv != "" {
		sb.WriteString(fmt.Sprintf("  api_key_env: %s\n", apiKeyEnv))
	}

	sb.WriteString("\ngateway:\n")
	sb.WriteString(fmt.Sprintf("  port: %d\n", port))
	sb.WriteString("  bind: 127.0.0.1\n")

	sb.WriteString("\ncontext:\n")
	sb.WriteString("  max_tokens_per_call: 8000\n")
	sb.WriteString("  history_retrieval_k: 10\n")
	sb.WriteString("  proactive_compaction: 0.5\n")

	sb.WriteString("\ntools:\n")
	sb.WriteString("  max_output_size: 102400\n")
	sb.WriteString("  scrub_output: true\n")
	sb.WriteString("  exec:\n")
	sb.WriteString("    sandbox: none\n")
	sb.WriteString("    timeout: 30s\n")
	sb.WriteString("  browser:\n")
	sb.WriteString("    enabled: true\n")
	sb.WriteString("    headless: true\n")
	sb.WriteString("    timeout: 30s\n")

	sb.WriteString("\nchannels:\n")
	sb.WriteString("  allow_all: true\n")
	if enableTelegram {
		sb.WriteString("  telegram:\n")
		sb.WriteString("    token_env: TELEGRAM_BOT_TOKEN\n")
	}
	if enableDiscord {
		sb.WriteString("  discord:\n")
		sb.WriteString("    token_env: DISCORD_BOT_TOKEN\n")
		sb.WriteString("    app_id_env: DISCORD_APP_ID\n")
	}
	if enableWhatsApp {
		sb.WriteString("  whatsapp:\n")
		sb.WriteString("    enabled: true\n")
		sb.WriteString("    # data_dir: ~/.openclio  # optional, defaults to ~/.openclio\n")
	}
	if enableWebChat {
		sb.WriteString("  # WebChat UI is always available when running `openclio serve`\n")
	}

	sb.WriteString("\nlogging:\n")
	sb.WriteString("  level: info\n")
	sb.WriteString("  output: ~/.openclio/openclio.log\n")

	// Write config file
	if err := os.WriteFile(configPath, []byte(sb.String()), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "error writing config: %v\n", err)
		os.Exit(1)
	}

	identityPath := filepath.Join(dataDir, "identity.md")
	userPath := filepath.Join(dataDir, "user.md")
	memoryPath := filepath.Join(dataDir, "memory.md")
	identity := fmt.Sprintf(
		"You are %s, a personal AI agent. Be concise, accurate, and practical.\n"+
			"You can switch your own AI model mid-conversation using the switch_model tool.\n"+
			"You can connect messaging channels like Slack, Telegram, Discord, or WhatsApp using the connect_channel tool.\n"+
			"For WhatsApp, no token is needed: connect first, then guide the user to scan the QR shown in openclio webchat.\n"+
			"For large multi-part requests, you can delegate parallel sub-tasks using the delegate tool.\n"+
			"When users ask for these actions, do them instead of refusing.",
		assistantName,
	)
	_ = os.WriteFile(identityPath, []byte(identity+"\n"), 0600)
	_ = os.WriteFile(userPath, []byte(userProfile+"\n"), 0600)
	if _, err := os.Stat(memoryPath); os.IsNotExist(err) {
		_ = os.WriteFile(memoryPath, []byte(""), 0600)
	}

	// ── Success + next steps ──────────────────────────────────────────────────
	fmt.Println("Config written to " + configPath)
	fmt.Println()

	if apiKeyEnv != "" {
		fmt.Printf("Next: set your API key\n")
		fmt.Printf("    export %s=<your-key>\n", apiKeyEnv)
		if apiKeyHint != "" {
			fmt.Printf("    Get one at: %s\n", apiKeyHint)
		}
		fmt.Println()
	}

	if enableTelegram {
		fmt.Println("Telegram: set TELEGRAM_BOT_TOKEN=<your-token>")
		fmt.Println("    Get a token from @BotFather on Telegram")
		fmt.Println()
	}
	if enableDiscord {
		fmt.Println("Discord: set DISCORD_BOT_TOKEN=<your-token>")
		fmt.Println("    Get a token at https://discord.com/developers/applications")
		fmt.Println()
	}
	if enableWhatsApp {
		fmt.Println("WhatsApp: no token required for current QR-login mode")
		fmt.Println("    Start `openclio serve` and scan the QR shown in openclio webchat")
		fmt.Println()
	}

	fmt.Printf("✓ %s is ready. Try: openclio chat\n", assistantName)
}

// ── Prompt helpers ───────────────────────────────────────────────────────────

var initReader = bufio.NewReader(os.Stdin)

func promptString(label, defaultVal string) string {
	fmt.Printf("   %s: ", label)
	line, _ := initReader.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultVal
	}
	return line
}

func promptConfirm(label string, defaultYes bool) bool {
	hint := "y/N"
	if defaultYes {
		hint = "Y/n"
	}
	fmt.Printf("   %s [%s]: ", label, hint)
	line, _ := initReader.ReadString('\n')
	line = strings.ToLower(strings.TrimSpace(line))
	if line == "" {
		return defaultYes
	}
	return line == "y" || line == "yes"
}

func promptChoice(label string, choices []string, defaultChoice string) string {
	fmt.Printf("   %s [%s]: ", label, defaultChoice)
	line, _ := initReader.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultChoice
	}
	for _, c := range choices {
		if line == c {
			return c
		}
	}
	fmt.Printf("   Invalid choice '%s', using default '%s'\n", line, defaultChoice)
	return defaultChoice
}

func promptMultiline(prefix string) string {
	var lines []string
	for {
		fmt.Print(prefix)
		line, _ := initReader.ReadString('\n')
		line = strings.TrimRight(line, "\r\n")
		if strings.TrimSpace(line) == "" {
			break
		}
		lines = append(lines, line)
	}
	return strings.TrimSpace(strings.Join(lines, "\n"))
}
